#!/usr/bin/env ruby

require File.expand_path('../../config/environment',  __FILE__)
require 'adhearsion'
require 'adhearsion/cli_commands'

require './lib/amqp'
AMQPManager.start
Adhearsion::CLI::AhnCommand.start
