#!/usr/bin/env ruby

STDOUT.sync = true
STDERR.sync = true

require File.expand_path('../../config/environment',  __FILE__)
require 'adhearsion/cli_commands'

require './lib/redis_connection'
require './lib/amqp_manager'

AmqpManager.start
Adhearsion::CLI::AhnCommand.start
