#!/usr/bin/env ruby

STDOUT.sync = true
STDERR.sync = true

# See https://github.com/celluloid/timers/issues/20
#     method 'old_init' not defined in SortedSet:
require 'set'
SortedSet.new

require File.expand_path('../../config/environment',  __FILE__)
require 'adhearsion/cli_commands'

Thread.abort_on_exception = false # Set to true for debugging

Dir['./lib/*.rb'].each { |f| require f }

Thread.new { AmqpManager.start }
Adhearsion::CLI::AhnCommand.start
